[program:teanary-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /home/wwwroot/teanary/current/artisan queue:work redis --queue=high,scout,sync,low --sleep=3 --tries=3 --max-time=3600 --memory=512
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/home/wwwlogs/queue.log
stderr_logfile=/home/wwwlogs/queue-error.log
stopwaitsecs=3600
priority=998
