[program:octane]
process_name=%(program_name)s_%(process_num)02d
command=php /home/wwwroot/teanary/current/artisan octane:start --server=frankenphp --host=0.0.0.0 --port=8000 --workers=4 --max-requests=500
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/home/wwwroot/teanary/current/storage/logs/octane.log
stderr_logfile=/home/wwwroot/teanary/current/storage/logs/octane-error.log
stopwaitsecs=3600
priority=999
