[program:teanary-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /home/wwwroot/teanary/current/artisan queue:work redis --queue=high,scout,low --sleep=3 --tries=3 --max-time=3600 --memory=512
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=2
redirect_stderr=true
stdout_logfile=/home/wwwroot/teanary/current/storage/logs/queue.log
stderr_logfile=/home/wwwroot/teanary/current/storage/logs/queue-error.log
stopwaitsecs=3600
priority=998
